import Head from 'next/head';
import Image from 'next/image';
import LandingPage from '../components/Landingpage/landingpage';
import { gql } from '@apollo/client';
import client from '../apollo-client';
import FEATUREDEXPERIENCES from '../graphql_api/featuredexperiences';
import { FEATURED_EXPERIENCES_INTERFACE } from '../graphql_api/featuredexperiences';
import { HOMEPAGEINTERFACE } from '../graphql_api/homePage';
import { HOMEPAGE } from '../graphql_api/homePage';

interface IProps {
  getInitialData: any;
  allfeaturedata: any;
  featuredExp: any;
  citydropdown: any;
  HomePage: any;
}
export default function Home({
  allfeaturedata,
  featuredExp,
  citydropdown,
  HomePage
}: IProps) {
  // const { featuredExp, citydropdown, HomePage } = getInitialData;
  return (
    <>
      <Head>
        <title className="text-3xl font-bold underline">See Sight Tours</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingPage
          allfeaturedata={allfeaturedata}
          featuredExp={featuredExp}
          citydropdown={citydropdown}
          HomePage={HomePage}
        />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { data } = await client.query<FEATURED_EXPERIENCES_INTERFACE>({
    query: FEATUREDEXPERIENCES,
    variables: {
      dayTours: true,
      multiday: true,
      airportTransfers: false
    }
  });
  const { data: HomePage } = await client.query<HOMEPAGEINTERFACE>({
    query: HOMEPAGE,
    variables: {
      guides: false
    }
  });
  return {
    props: {
      allfeaturedata: data,
      featuredExp: data.homePage,
      citydropdown: data.citiesDropdown,
      HomePage: HomePage
    }
  };
}
