import Head from 'next/head';
import Image from 'next/image';
<<<<<<< Updated upstream
import { gql } from '@apollo/client';
import client from '../apollo-client';
interface IProps {
  blogs: any;
}
export default function Home({ blogs }: IProps) {
=======
import PageHero from '../components/Contact/PageHero';
export default function Home() {
>>>>>>> Stashed changes
  return (
    <>
      <Head>
        <title className="text-3xl font-bold underline">See Sight Tours</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageHero title={''} snippet={''} media={undefined} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query BLOGS_PAGE {
        blogsPage {
          id
          header
          subheader
          page_title
        }
      }
    `
  });
  return {
    props: {
      blogsPage: data.blogsPage
    }
  };
}
